/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--color-background)",
        card: "var(--color-card)",
        text: "var(--color-text)",
        muted: "var(--color-muted)",
        accent: "var(--color-accent)",
        acttive: "var(--color-acttive)",
        dark: "var(--color-dark)",
        border: "var(--color-border)",
        heading: "var(--color-heading)",
        subheading: "var(--color-subheading)",
        paragraph: "var(--color-paragraph)",
        // Icon colors
        "icon-primary": "var(--color-accent)",
        "icon-secondary": "var(--color-muted)",
        "icon-success": "var(--color-acttive)",
        "icon-danger": "var(--color-danger)",
        "icon-warning": "var(--color-warning)",
        "icon-info": "var(--color-info)",
      },
      boxShadow: {
        card: "0 4px 24px 0 var(--color-shadow)",
        "card-hover": "0 8px 32px 0 var(--color-shadow-hover)",
        btn: "0 2px 8px 0 var(--color-btn-shadow, var(--color-shadow))",
        "btn-hover": "0 4px 16px 0 var(--color-btn-shadow, var(--color-shadow-hover))",
        input: "0 1px 3px 0 var(--color-input-shadow, var(--color-shadow))",
        "input-focus": "0 0 0 2px var(--color-input-focus-shadow, var(--color-accent))",
        modal: "0 8px 40px 0 var(--color-modal-shadow, var(--color-shadow))",
        "modal-hover": "0 12px 48px 0 var(--color-modal-shadow, var(--color-shadow-hover))",
      },
      backgroundImage: {
        background: "linear-gradient(145deg, var(--color-background), var(--color-background-gradient-to, var(--color-background)))",
        'gradient-1': 'linear-gradient(135deg, var(--gradient-1-from), var(--gradient-1-to))',
        'gradient-2': 'linear-gradient(135deg, var(--gradient-2-from), var(--gradient-2-to))',
        'gradient-3': 'linear-gradient(135deg, var(--gradient-3-from), var(--gradient-3-to))',
        'gradient-4': 'linear-gradient(135deg, var(--gradient-4-from), var(--gradient-4-to))',
        'gradient-5': 'linear-gradient(135deg, var(--gradient-5-from), var(--gradient-5-to))',
        'gradient-6': 'linear-gradient(135deg, var(--gradient-6-from), var(--gradient-6-to))',
        'gradient-7': 'linear-gradient(135deg, var(--gradient-7-from), var(--gradient-7-to))',
        'gradient-8': 'linear-gradient(135deg, var(--gradient-8-from), var(--gradient-8-to))',
        'gradient-9': 'linear-gradient(135deg, var(--gradient-9-from), var(--gradient-9-to))',
        'gradient-10': 'linear-gradient(135deg, var(--gradient-10-from), var(--gradient-10-to))',
        'banner-effect': 'radial-gradient(circle at 20% 20%, var(--color-accent, #3b82f6) 0%, transparent 70%)',
        'header-bg': 'linear-gradient(90deg, var(--color-header-bg, var(--color-accent)) 0%, var(--color-background, #fff) 100%)',
        'footer-bg': 'linear-gradient(90deg, var(--color-footer-bg, var(--color-accent)) 0%, var(--color-background, #fff) 100%)',
      },
    },
  },
};
